version: "3.7"
services:
  postgres:
    image: postgres:latest
    container_name: shopify-app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 6102:5432
    networks:
      - shopify-app

  redis:
    image: redis:latest
    container_name: shopify-app-redis
    restart: unless-stopped
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: redis
    ports:
      - 6103:6379
    networks:
      - shopify-app

  api:
    build:
      context: ./
      dockerfile: Dockerfile-local
    image: shopify-app
    container_name: shopify-app-api
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - 6105:9000
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
      - redis
    networks:
      - shopify-app

  nginx:
    image: nginx:alpine
    container_name: shopify-app-nginx
    restart: unless-stopped
    ports:
      - 6101:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    depends_on:
      - api
    networks:
      - shopify-app

networks:
  shopify-app:
    driver: bridge
