version: "3.7"
services:
  scaffolding-postgres:
    image: postgres:latest
    container_name: scaffolding-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 6102:5432
    networks:
      - scaffolding

  scaffolding-redis:
    image: redis:latest
    container_name: scaffolding-redis
    restart: unless-stopped
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: redis
    ports:
      - 6103:6379
    networks:
      - scaffolding

  scaffolding-api:
    build:
      context: ./
      dockerfile: Dockerfile-local
    image: scaffolding
    container_name: scaffolding-api
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - 6105:9000
    volumes:
      - ./:/var/www
    depends_on:
      - scaffolding-postgres
      - scaffolding-redis
    networks:
      - scaffolding

  scaffolding-nginx:
    image: nginx:alpine
    container_name: scaffolding-nginx
    restart: unless-stopped
    ports:
      - 6101:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    depends_on:
      - scaffolding-api
    networks:
      - scaffolding

networks:
  scaffolding:
    driver: bridge
